// // File generated by FlutterFire CLI.
// // ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
// import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
// import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;
//
// /// Placeholder [FirebaseOptions] for use with your Firebase apps.
// ///
// /// To use real Firebase services, replace the placeholders with your
// /// Firebase project configurations and rename this file to firebase_options.dart.
// ///
// /// Example:
// /// ```dart
// /// import 'firebase_options.dart';
// /// // ...
// /// await Firebase.initializeApp(
// ///   options: DefaultFirebaseOptions.currentPlatform,
// /// );
// /// ```
// class DefaultFirebaseOptions {
//   static FirebaseOptions get currentPlatform {
//     if (kIsWeb) {
//       return web;
//     }
//     switch (defaultTargetPlatform) {
//       case TargetPlatform.android:
//         return android;
//       case TargetPlatform.iOS:
//         return ios;
//       case TargetPlatform.macOS:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for macos - '
//           'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//       case TargetPlatform.windows:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for windows - '
//           'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//       case TargetPlatform.linux:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for linux - '
//           'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//       default:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions are not supported for this platform.',
//         );
//     }
//   }
//
//   static const FirebaseOptions web = FirebaseOptions(
//     apiKey: 'YOUR_API_KEY',
//     appId: 'YOUR_APP_ID',
//     messagingSenderId: 'YOUR_SENDER_ID',
//     projectId: 'YOUR_PROJECT_ID',
//     authDomain: 'YOUR_AUTH_DOMAIN',
//     storageBucket: 'YOUR_STORAGE_BUCKET',
//   );
//
//   static const FirebaseOptions android = FirebaseOptions(
//     apiKey: 'YOUR_API_KEY',
//     appId: 'YOUR_APP_ID',
//     messagingSenderId: 'YOUR_SENDER_ID',
//     projectId: 'YOUR_PROJECT_ID',
//     storageBucket: 'YOUR_STORAGE_BUCKET',
//   );
//
//   static const FirebaseOptions ios = FirebaseOptions(
//     apiKey: 'YOUR_API_KEY',
//     appId: 'YOUR_APP_ID',
//     messagingSenderId: 'YOUR_SENDER_ID',
//     projectId: 'YOUR_PROJECT_ID',
//     storageBucket: 'YOUR_STORAGE_BUCKET',
//     iosBundleId: 'YOUR_IOS_BUNDLE_ID',
//   );
// }
