// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDKU0_iP2J6J_gX0nw21HRLFQgcozeKZIU',
    appId: '1:699520918683:web:3889c0fafcf42e8f82523e',
    messagingSenderId: '699520918683',
    projectId: 'meteo-du-numerique-84da1',
    authDomain: 'meteo-du-numerique-84da1.firebaseapp.com',
    storageBucket: 'meteo-du-numerique-84da1.firebasestorage.app',
    measurementId: 'G-B0R8NR5YDP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDHSOta-63fwC2j_9yfdjehNnQc4dNH4m0',
    appId: '1:699520918683:android:b4a8228923c2a0dd82523e',
    messagingSenderId: '699520918683',
    projectId: 'meteo-du-numerique-84da1',
    storageBucket: 'meteo-du-numerique-84da1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBM9WqmtXGxSy8xm_a6dGwTIpt0IjmmwXU',
    appId: '1:699520918683:ios:8fd22c09a39879ff82523e',
    messagingSenderId: '699520918683',
    projectId: 'meteo-du-numerique-84da1',
    storageBucket: 'meteo-du-numerique-84da1.firebasestorage.app',
    androidClientId: '699520918683-65umma4i0ra3l87gj0k2arnu3j02sm86.apps.googleusercontent.com',
    iosBundleId: 'fr.acrennes.MeteoDuNumeriqueUITests',
  );

}