// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBGQy4kEn-NkXmkkAbX1j8B6FyFQ9JoWXA',
    appId: '1:665353360218:web:8f86ac4c9302f10f2c9963',
    messagingSenderId: '665353360218',
    projectId: 'meteo-du-numerique-acrennes',
    authDomain: 'meteo-du-numerique-acrennes.firebaseapp.com',
    storageBucket: 'meteo-du-numerique-acrennes.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCRznsFBjp44MJST8CKI30J2CqkqGEnmZ0',
    appId: '1:665353360218:android:b69d64c3a8802f142c9963',
    messagingSenderId: '665353360218',
    projectId: 'meteo-du-numerique-acrennes',
    storageBucket: 'meteo-du-numerique-acrennes.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA9vSsATznQTmBhXPYiGsEElKV8dnRHj8w',
    appId: '1:665353360218:ios:89091a8dbdb476642c9963',
    messagingSenderId: '665353360218',
    projectId: 'meteo-du-numerique-acrennes',
    storageBucket: 'meteo-du-numerique-acrennes.firebasestorage.app',
    iosBundleId: 'com.example.meteoDuNumerique',
  );

}