version: '2'

services:
  meteo-du-numerique-json-server:
    image: williamyeh/json-server
    command: [ "--watch", "./db2.json", "--routes","./routes.json" ]
    volumes:
      - ./json-config:/data
    ports:
      - 1234:3000
    network_mode: bridge